import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

// Import the file that will be generated by the build runner
// NOTE: This file (injection.config.dart) does not exist yet!
import 'injection.config.dart';

// Create the GetIt instance
final getIt = GetIt.instance;

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
void configureDependencies() => getIt.init();